### ISSUE TITLE
[Question] Got error when running program

### ISSUE THREAD

**Issue by Quicksilver151** [MeemeeLab/node-anime-viewer#12]
ran the index.js with node and this was the result

/usr/local/lib/node_modules/node-anime-viewer/src/index.js:2
import anime from './modules/anime.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by MeemeeLab** [comment]
To run this without installing npm package, You have to run `npm start` in directory that package.json exists.
If you can install npm package, I recommend installing it. 
`npm install node-anime-viewer` then run `node-anime-viewer‘.

**Comment by Quicksilver151** [comment]
ok
i did try to install it
anyway
i found the source of the issue
seems like i didnt have the latest version of node
i tried updating it with apt but apt thinks node 10 is the latest version
had to install node 14 manually for it to work
