### ISSUE TITLE
[Bug] Selecting naruto shippuden crashes (0 episodes)

### ISSUE THREAD

**Issue by MeemeeLab** [MeemeeLab/node-anime-viewer#23]
selecting naruto shippuden for some reason crashed the program
this is the error i get
```
node-anime-viewer 1.0.3
Copyright (C) 2021 [object Object]

Select episode: 
(node:1005698) UnhandledPromiseRejectionWarning: TypeError: [terminal] gridMenu(): argument #0 should be a non-empty array
    at Terminal.gridMenu (/usr/local/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/gridMenu.js:83:70)
    at SelectEpisodeInterface.Init (file:///usr/local/lib/node_modules/node-anime-viewer/src/modules/interface.js:51:19)
    at new Interface (file:///usr/local/lib/node_modules/node-anime-viewer/src/modules/interface.js:19:14)
    at new SelectEpisodeInterface (file:///usr/local/lib/node_modules/node-anime-viewer/src/modules/interface.js:48:8)
    at Object.selectAnime (file:///usr/local/lib/node_modules/node-anime-viewer/src/index.js:50:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1005698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1005698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

_Originally posted by @Quicksilver151 in https://github.com/MeemeeLab/node-anime-viewer/issues/21#issuecomment-1002471329_

**Comment by MeemeeLab** [comment]
Merging to #21, https://github.com/MeemeeLab/node-anime-viewer/issues/21#issuecomment-1002525037.
