### ISSUE TITLE
[Request] Can't play on android (Add proxy feature)

### ISSUE THREAD

**Issue by asdfugil** [MeemeeLab/node-anime-viewer#37]
So, it looks like playing on android is broken again.

```
/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:646                                                                         throw error ;
                ^

TypeError: Cannot read properties of null (reading 'split')
    at playVideo (file:///data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/src/index.js:224:99)
    at SelectActionInterface.play (file:///data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/src/index.js:127:13)
    at file:///data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/src/modules/interface.js:255:34
    at cleanup (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/singleColumnMenu.js:307:21)
    at submit (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/singleColumnMenu.js:429:39)
    at Object.onKey (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/singleColumnMenu.js:474:5)
    at Function.NextGenEvents.listenerWrapper (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:481:33)
    at Function.NextGenEvents.emitToOneListener (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:796:17)
    at Function.NextGenEvents.emitEvent (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:639:18)
    at Terminal.NextGenEvents.emit (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:512:23)                 
Node.js v17.3.0
```

So I tried to fix that error by optional chaining. Another error appeared and it happens that you cannot pass referer headers to android VLC but you also need referer headers. I tried to make a http proxy [here](https://github.com/asdfugil/node-anime-viewer/blob/referer/src/modules/http-proxy.js) (also filled with debug code).
And that just results in a cloudfare 522 error.

**Comment by asdfugil** [comment]
Actually, it still would not play on Android

```
node-anime-viewer 1.2.8
Copyright (C) 2021 MeemeeLab and Contributors


Trying to play: Dr. Stone 1/24/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:646
                throw error ;
                ^

TypeError: Cannot read properties of null (reading 'split')
    at playVideo (file:///data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/src/index.js:228:152)
    at SelectActionInterface.play (file:///data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/src/index.js:129:13)
    at file:///data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/src/modules/interface.js:278:34
    at cleanup (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/singleColumnMenu.js:307:21)
    at submit (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/singleColumnMenu.js:429:39)
    at Object.onKey (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/terminal-kit/lib/singleColumnMenu.js:474:5)
    at Function.NextGenEvents.listenerWrapper (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:481:33)
    at Function.NextGenEvents.emitToOneListener (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:796:17)
    at Function.NextGenEvents.emitEvent (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:639:18)
    at Terminal.NextGenEvents.emit (/data/data/com.termux/files/usr/lib/node_modules/node-anime-viewer/node_modules/nextgen-events/lib/NextGenEvents.js:512:23)

Node.js v17.4.0
```
