### ISSUE TITLE
[Bug] Trouble with leaving program running for long periods of time.

### ISSUE THREAD

**Issue by FireboltAA** [MeemeeLab/node-anime-viewer#38]
This is not something I have tested extensively, but it seems that if I pause the anime I'm watching and leave for a long period of time (30 min+ maybe), with the anime open in vlc and the program running in the background, when vlc closes and I try to repeat the episode or go to the next episode (have not tested with previous episode), it returns this error and crashes:
```
file:///home/fireboltaa/.npm/_npx/32ed869cd1e31f8f/node_modules/node-anime-viewer/src/modules/anime.js:47
        CryptoJS.enc.Utf8.stringify(CryptoJS.AES.decrypt($('script[data-name=\x27crypto\x27]').data('value'), CryptoJS.enc.Utf8.parse(value6.toString() + value6.toString()), {
                                                                                                                                             ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at generateEncryptAjaxParameters (file:///home/fireboltaa/.npm/_npx/32ed869cd1e31f8f/node_modules/node-anime-viewer/src/modules/anime.js:47:142)
    at AnimeEpisode.getAvailableVideos (file:///home/fireboltaa/.npm/_npx/32ed869cd1e31f8f/node_modules/node-anime-viewer/src/modules/anime.js:150:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/fireboltaa/.npm/_npx/32ed869cd1e31f8f/node_modules/node-anime-viewer/src/index.js:102:34

**Comment by MeemeeLab** [comment]
I wasn't able to reproduce that error on windows, It might be problem only happens on linux.

**Comment by FireboltAA** [comment]
Alright, I'm assuming that this is just a linux problem now, and since it is not a huge problem for most people, I'll close this for now.
